# Generated by Django 5.1.2 on 2024-11-12 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_genre_id_movierecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierecommendation',
            name='expireAt',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 11, 13, 4, 49, 49, 572537, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='movierecommendation',
            name='voteAverage',
            field=models.FloatField(default=0.0, verbose_name='Vote Average'),
        ),
    ]
