# Generated by Django 5.1.2 on 2024-11-18 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movierecommendation_expireat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierecommendation',
            name='imageUrl',
            field=models.CharField(default='https://image.tmdb.org/t/p/w500/j523NJfe7KRUfBLSOPsGxrTgoyR.jpg', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movierecommendation',
            name='expireAt',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 11, 19, 3, 45, 51, 147533, tzinfo=datetime.timezone.utc)),
        ),
    ]
