# Generated by Django 5.1.2 on 2024-11-26 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movierecommendation_imageurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierecommendation',
            name='type',
            field=models.CharField(choices=[('recommendation', 'Recommendation'), ('trending', 'Trending'), ('other', 'Other')], default='recommendation', max_length=50),
        ),
        migrations.AlterField(
            model_name='movierecommendation',
            name='expireAt',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='movierecommendation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
