# Generated by Django 5.1.2 on 2024-11-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_movierecommendation_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
